name: Build

on:
  workflow_run:
    workflows: ["Setup"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Import setup config
        uses: ./.github/workflows/setup.yml

      - name: Build
        run: cargo build --verbose

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Tests
        run: cargo test --verbose

      - name: Fmt
        run: cargo fmt -- --check
