name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Import setup config
        uses: ./.github/workflows/setup.yml

      - name: Build
        run: cargo build --verbose

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Tests
        run: cargo test --verbose

      - name: Fmt
        run: cargo fmt -- --check
