name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Fmt
        run: cargo fmt -- --check
